import action_keywords from "@/actions/gpt/keywords";
// import action_summary from "@/actions/gpt/summary";
// import action_insights from "../../actions/gpt/insights"

export default async function Home() {
    const logs = "Mexico's market continues to grow robustly in value terms, but volume growth appears to be lagging. VMI estimates 2007 market growth at 8.7% year-on-year worldwide, reaching a value of $13.3 billion U.S. dollar. The new five-year forecast for the period 2007 to 2012 sees average annual growth in dollar terms of 5.4% and in local currency terms of 7.4%. According to IMS Health, the market grew 7.5% in value terms worldwide over the first seven months of 2007, while the number of units sold edged up only 0.7%. Local market sources indicate that volumes remain nearly static despite record spending by the state sector. I did a SWOT analysis of Mexico pharmaceuticals and healthcare industry. The slide shows my findings. Strengths Mexico is the largest market in Latin America along with Brazil, with estimated 8.9% growth in 2007. Mexico is one of Latin America's most developed markets and regulatory standards are superior to most of its southern neighbors. Mexico has strong trade links outside Latin America to the U.S., Canada, and EU. Mexico has a competitive and well-developed pharmaceutical industry, including around 200 companies and a substantial multinational presence. Weakness Despite important recent reforms, the enforcement of domestic patent law remains problematic and counterfeiting is a continuing problem. With nearly half of the population lacking health insurance, Mexico's drug market is particularly sensitive to economic shocks. The Mexican government's drug pricing policy is focusing on cost containment, while an efficient supply chain leads to high price for consumers. The expansion of state health coverage has focused on basic, essential drugs and reimbursement for many high-tech imported drugs remains limited or non-existent. Opportunities The generics market has strong growth potential as both the government and consumers look to the sector to provide cost-effective coverage in place of less reliable copy drugs. New legislation on bioequivalence has recently been approved in Mexico and may push a number of similar or copy products off the market over the next three to five years. Health sector reform and the expansion of programs such as Segro Popular will drive overall health spending. Other reforms including better data protection rules could further boost investment in the sector. Threats Continuing failures to enforce domestic patent law more robustly will continue to limit both investment and product launches by multinationals. The government will be limited in implementing health care reform by tightly constrained funding, corruption and the multiple lawyers of government involved. Mexico has in the past been subject to periodic economic crises and a regional financial crisis. Particularly devaluation in the value of the peso could derail market growth."
    const calls = (await action_keywords("66f99c8dfa0330919964ea02", logs));
    console.log(calls);
    return (
        <div>

        </div>
    );
}
